[package]
name = "ppl-game"
version = "0.1.0"
edition = "2021"

[features]
default = []
tui = [ 'dep:termios' ]

[dependencies]
termios = { version = "0.3", optional = true }
rand = { version = "0.8.5" }
